# -*- coding: utf-8 -*-
"""600747_ลัญจกร_Hack2_ver.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfhIItbnq25CoDNpQUVu-vhXIk26Z2XT

# Main data pipeline
"""

# 🎯 1. ติดตั้งไลบรารี
!pip install -U transformers easyocr thefuzz

import os
import shutil
import cv2
import json
import re
import numpy as np
import pandas as pd
import easyocr
from PIL import Image
from google import genai
from google.colab import files
from google.colab import userdata
from google.colab import drive
from thefuzz import fuzz
import getpass
import torch
import gc

# ==========================================
# 0. MOUNT GOOGLE DRIVE (สร้างจุด Checkpoint แบบถาวร)
# ==========================================
print("📂 กำลังเชื่อมต่อ Google Drive...")
drive.mount('/content/drive')
drive_save_path = '/content/drive/MyDrive/OCR_Checkpoint'
os.makedirs(drive_save_path, exist_ok=True)
print(f"✅ สร้างโฟลเดอร์ Checkpoint ที่: {drive_save_path}")

# ==========================================
# 1. CONFIGURATION
# ==========================================
CONFIG = {
    "img_dir": "/content/images",
    "debug_dir": "/content/debug_images",
    "crop_dir": "/content/cropped_images",
    "csv_path": "/content/submission_template_v4.csv",
    # 🎯 ย้ายไฟล์สำคัญ 3 ตัวนี้ไปเซฟลง Google Drive เพื่อกันเน็ตหลุด
    "output_csv": f"{drive_save_path}/submission.csv",
    "validation_csv": f"{drive_save_path}/validation.csv",
    "json_log_path": f"{drive_save_path}/outputOCR.json",
    "easyocr_conf_threshold": 0.85
}

# ==========================================
# 2. GPU CHECK & KAGGLE SETUP
# ==========================================
print("🖥️ Checking GPU Status...")
if torch.cuda.is_available():
    print(f"✅ GPU is ON: {torch.cuda.get_device_name(0)}\n")
else:
    print("❌ WARNING: GPU is NOT ENABLED!")
    print("👉 กรุณาเปิด T4 GPU ใน Google Colab ก่อนรัน\n")

print("🔑 Kaggle API Setup (เปิดไฟล์ kaggle.json เพื่อดูค่า)")
os.environ['KAGGLE_USERNAME'] = getpass.getpass('Kaggle Username: ')
os.environ['KAGGLE_KEY'] = getpass.getpass('Kaggle Key: ')

# ==========================================
# 3. DATASET SETUP
# ==========================================
for folder in [CONFIG["img_dir"], CONFIG["debug_dir"], CONFIG["crop_dir"]]:
    os.makedirs(folder, exist_ok=True)

print("\n📥 Downloading dataset from Kaggle...")
os.system("kaggle competitions download -c super-ai-engineer-season-6-ocr-2569-round2")

print("📦 Extracting dataset...")
os.system("unzip -q -o super-ai-engineer-season-6-ocr-2569-round2.zip -d /content/kaggle_data")

for root, dirs, files_in_dir in os.walk("/content/kaggle_data"):
    for filename in files_in_dir:
        filepath = os.path.join(root, filename)
        if filename.lower().endswith(".csv"):
            shutil.move(filepath, CONFIG["csv_path"])
        elif filename.lower().endswith((".png", ".jpg", ".jpeg")):
            dest_path = os.path.join(CONFIG["img_dir"], filename)
            shutil.move(filepath, dest_path)
print("✅ Dataset Ready!")

# ==========================================
# 4. INITIALIZATION & HELPERS
# ==========================================
reader = easyocr.Reader(['th', 'en'], gpu=True) # 🎯 โหลดโมเดล EasyOCR
API_KEY = userdata.get("GEMINI_API_KEY")
client = genai.Client(api_key=API_KEY)

def clean_digit(raw):
    raw = str(raw).replace(',', '').replace(' ', '')
    raw = raw.replace('l', '1').replace('I', '1').replace('|', '1')
    raw = raw.replace('O', '0').replace('D', '0').replace('o', '0')
    # 🚀 FIX 1: เพิ่ม Confusion Matrix ดักจับตัวอักษรที่ OCR มักอ่านพลาดเป็นเลข
    raw = raw.replace('S', '5').replace('s', '5').replace('B', '8')
    raw = raw.replace('Z', '2').replace('z', '2').replace('q', '9')

    mapping_table = str.maketrans('๐๑๒๓๔๕๖๗๘๙o', '01234567890')
    cleaned = raw.translate(mapping_table)
    cleaned = re.sub(r'\D', '', cleaned)
    return cleaned if cleaned else "0"

def thai_text_to_number(text):
    if not text: return -1
    text = text.replace(" ", "").replace("ทมื่น", "หมื่น").replace("สิบย", "สิบ")

    num_map = {'ศูนย์':0, 'หนึ่ง':1, 'หนึง':1, 'เอ็ด':1, 'สอง':2, 'ยี่':2, 'สาม':3, 'สี่':4, 'ห้า':5, 'หก':6, 'เจ็ด':7, 'แปด':8, 'เก้า':9}
    pos_map = {'สิบ':10, 'ร้อย':100, 'พัน':1000, 'หมื่น':10000, 'แสน':100000, 'ล้าน':1000000}

    pattern = r'(ศูนย์|หนึ่ง|หนึง|เอ็ด|สอง|ยี่|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า|สิบ|ร้อย|พัน|หมื่น|แสน|ล้าน)'
    tokens = re.findall(pattern, text)
    if not tokens: return -1

    total = 0
    current_val = 0
    for token in tokens:
        if token in num_map:
            current_val = num_map[token]
        elif token in pos_map:
            if current_val == 0 and token == 'สิบ':
                current_val = 1
            total += current_val * pos_map[token]
            current_val = 0

    total += current_val
    return total

def parse_id(id_str):
    parts = id_str.split('_')
    if parts[0] == "constituency":
        return {"type": "constituency", "province": parts[1], "constituency": parts[2], "row": parts[3], "doc_key": f"constituency_{parts[1]}_{parts[2]}"}
    elif parts[0] == "party" and parts[1] == "list":
        return {"type": "party_list", "province": parts[2], "constituency": parts[3], "row": parts[4], "doc_key": f"party_list_{parts[2]}_{parts[3]}"}
    return {}

def get_doc_key_and_page(filename):
    base_name = os.path.splitext(filename)[0]
    match = re.search(r'(.*)_page(\d+)$', base_name, re.IGNORECASE)
    if match: return match.group(1), int(match.group(2))
    return base_name, 1

# ==========================================
# 5. PHASE 2: PER PAGE MERGE & ENHANCEMENT
# ==========================================
def extract_table_grid(image_paths, doc_key):
    images = []
    for path in image_paths:
        img = cv2.imread(path)
        if img is None: continue

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        h_img, w_img = gray.shape

        corner_mean = np.mean([
            np.mean(gray[0:10, 0:10]), np.mean(gray[0:10, -10:]),
            np.mean(gray[-10:, 0:10]), np.mean(gray[-10:, -10:])
        ])
        if corner_mean < 100:
            _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
            contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            if contours:
                c = max(contours, key=cv2.contourArea)
                if cv2.contourArea(c) > (h_img * w_img * 0.2):
                    x, y, w_c, h_c = cv2.boundingRect(c)
                    img = img[y:y+h_c, x:x+w_c]
            # 🚀 FIX 2: ลบ cv2.bitwise_not ออก ป้องกันภาพกลายเป็นสีดำตัวหนังสือขาวจน OCR หลอน

        images.append(img)

    if not images: return None

    max_w = max(img.shape[1] for img in images)
    padded_images = [cv2.copyMakeBorder(img, 0, 0, 0, max_w - img.shape[1], cv2.BORDER_CONSTANT, value=[255, 255, 255]) for img in images]
    merged_img = cv2.vconcat(padded_images)

    # ดักจับภาพใหญ่เกินขีดจำกัด SHRT_MAX ป้องกัน OpenCV พัง
    MAX_DIM = 32000
    if merged_img.shape[0] > MAX_DIM or merged_img.shape[1] > MAX_DIM:
        scale = MAX_DIM / max(merged_img.shape[0], merged_img.shape[1])
        merged_img = cv2.resize(merged_img, (int(merged_img.shape[1] * scale), int(merged_img.shape[0] * scale)), interpolation=cv2.INTER_AREA)

    gray_merged = cv2.cvtColor(merged_img, cv2.COLOR_BGR2GRAY)

    gray_merged = cv2.normalize(gray_merged, None, 0, 255, cv2.NORM_MINMAX)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    enhanced_img = clahe.apply(gray_merged)

    final_img = cv2.cvtColor(enhanced_img, cv2.COLOR_GRAY2BGR)

    del images, padded_images, merged_img, gray_merged, enhanced_img
    gc.collect()

    return final_img

# ==========================================
# 6. PHASE 3 & 4: OCR & GEMINI FALLBACK
# ==========================================
def run_easyocr_validation(table_roi, doc_key, expected_row_count):
    if table_roi is None: return {}, 0.0, False, [], []

    results = reader.readtext(table_roi, width_ths=1.5, x_ths=2.0)
    score_blocks = []
    anchor_y = 0
    stop_y = float('inf')
    anchor_found = False

    for bbox, text, conf in results:
        raw_text = text.strip()
        clean_text = raw_text.replace(" ", "")
        if "รวมคะแนนทั้งสิ้น" in clean_text or fuzz.partial_ratio("รวมคะแนนทั้งสิ้น", clean_text) >= 80:
             stop_y = min(stop_y, bbox[0][1])

    for bbox, text, conf in results:
        raw_text = text.strip()
        y_center = (bbox[0][1] + bbox[2][1]) / 2
        clean_text = raw_text.replace(" ", "")

        if "ได้คะแนน" in clean_text or fuzz.partial_ratio("ได้คะแนน", clean_text) >= 80:
            anchor_y = max(bbox[2][1], bbox[3][1])
            anchor_found = True
            continue

        if anchor_found and anchor_y < y_center < stop_y:
            match = re.search(r'([0-9๐-๙oOlISsBq|,\s]+)(?:[\(\[\{\|\u0e31\s]+)?([ก-๙]+)(?:[\)\]\}\|\u0e31\s]+)?', raw_text)
            if match:
                score_blocks.append({
                    "y": y_center,
                    "digit": clean_digit(match.group(1)),
                    "word": match.group(2).replace(" ", ""),
                    "conf": float(conf),
                    "raw_text": raw_text
                })

    score_blocks = sorted(score_blocks, key=lambda x: x['y'])

    extracted_data = {}
    conf_list = []
    is_valid = True
    val_rows = []

    if len(score_blocks) == expected_row_count:
        for i, block in enumerate(score_blocks):
            party_no = str(i + 1)
            digit_val = int(block['digit']) if block['digit'] else 0
            parsed_thai_num = thai_text_to_number(block['word'])

            status = "PASS"
            if parsed_thai_num != -1 and parsed_thai_num != digit_val:
                is_valid = False
                status = "MISMATCH"

            extracted_data[party_no] = {"numeric": block['digit']}
            conf_list.append(block['conf'])

            val_rows.append({
                "Doc Key": doc_key, "Row": party_no, "OCR Raw Text": block['raw_text'],
                "OCR Digit": block['digit'], "OCR Word": block['word'],
                "Parsed Thai Num": parsed_thai_num if parsed_thai_num != -1 else "อ่านไม่ออก",
                "OCR Conf": f"{block['conf']:.2f}", "Status": status
            })
        avg_conf = sum(conf_list) / len(conf_list) if conf_list else 0.0
    else:
        is_valid = False
        avg_conf = sum([b['conf'] for b in score_blocks]) / len(score_blocks) if score_blocks else 0.0

    return extracted_data, avg_conf, is_valid, score_blocks, val_rows

# 🎯 ระบบสลับ Model 2.5 Flash -> 2.5 Pro
def call_gemini_fallback(doc_key, crop_img_path, ocr_json_data, expected_rows_data):
    print(f"   🤖 Gemini Fallback: {doc_key} (แก้ไขข้อผิดพลาดของ OCR)")
    expected_keys = [str(r[2]) for r in expected_rows_data]

    prompt = f"""
    You are an expert OCR validator for Thai election tally sheets.
    Your task is to extract the FINAL VOTE COUNT for each party row.
    Expected row numbers: {", ".join(expected_keys)}.

    Context from EasyOCR (may contain errors or missing rows):
    {json.dumps(ocr_json_data, ensure_ascii=False)}

    INSTRUCTIONS:
    1. Read the attached image carefully. Look at the column that contains the vote counts.
    2. Convert Thai text numbers into Arabic numerals to cross-check.
    3. Return ONLY a valid JSON object matching this exact schema:
    {{"data": {{"1": {{"numeric": "10"}}, "2": {{"numeric": "0"}}, ... }}}}
    """

    img_content = Image.open(crop_img_path)

    try:
        # 🎯 ลองเรียกใช้ Gemini 3.0 Flash ก่อนเสมอ
        resp = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=[prompt, img_content],
            config={"temperature": 0.0, "response_mime_type": "application/json"}
        )
        text_resp = resp.text.replace("```json", "").replace("```", "").strip()
        return json.loads(text_resp).get("data", {})

    except Exception as e:
        print(f"   ⚠️ Gemini 3.0 Flash Error: {e}")
        print("   🔄 Switching to Gemini 2.5 flash..")
        try:
            # 🎯 ถ้า Flash เกิด Error จะสลับมาใช้ Gemini 2.5 flash ในรอบนี้
            resp_pro = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=[prompt, img_content],
                config={"temperature": 0.0, "response_mime_type": "application/json"}
            )
            text_resp_pro = resp_pro.text.replace("```json", "").replace("```", "").strip()
            return json.loads(text_resp_pro).get("data", {})

        except Exception as e_pro:
            print(f"   ❌ Gemini 2.5 flash also Failed: {e_pro}")
            return {}

# ==========================================
# 7. PHASE 5: INTEGRATION & EXECUTION
# ==========================================
def process_pipeline(doc_groups, image_map):
    results_map = {}
    total_rows_processed = 0
    last_notified_rows = 0

    checkpoint_log = {}
    if os.path.exists(CONFIG["json_log_path"]):
        try:
            with open(CONFIG["json_log_path"], "r", encoding="utf-8") as f:
                checkpoint_log = json.load(f)
        except json.JSONDecodeError: checkpoint_log = {}

    global_val_list = []
    if os.path.exists(CONFIG["validation_csv"]):
        try: global_val_list = pd.read_csv(CONFIG["validation_csv"]).to_dict('records')
        except pd.errors.EmptyDataError: pass

    for doc_key, rows in doc_groups.items():
        if doc_key in checkpoint_log and "final_results" in checkpoint_log[doc_key]:
            for template_id, vote in checkpoint_log[doc_key]["final_results"].items():
                results_map[template_id] = vote
            total_rows_processed += len(rows)
            continue

        pages = image_map.get(doc_key, [])
        if not pages: continue

        print(f"Processing: {doc_key} (Expect {len(rows)} rows)")

        table_roi = extract_table_grid(pages, doc_key)

        # 🚀 FIX 3: เอามีดสับเฉพาะ 60% ฝั่งขวาของตาราง เพื่อลด Noise ชื่อพรรค และลดภาระ Gemini
        if table_roi is not None:
            h_roi, w_roi = table_roi.shape[:2]
            table_roi = table_roi[:, int(w_roi * 0.40):]

        crop_path = os.path.join(CONFIG["crop_dir"], f"crop_{doc_key}.png")
        if table_roi is not None: cv2.imwrite(crop_path, table_roi)

        extracted_data, conf, is_valid, raw_ocr_blocks, val_rows = run_easyocr_validation(table_roi, doc_key, len(rows))

        used_gemini = False
        if not is_valid or conf < CONFIG["easyocr_conf_threshold"]:
            used_gemini = True
            print(f"   ⚠️ OCR Check Failed (Valid: {is_valid}, Conf: {conf:.2f}). Triggering Gemini...")
            gemini_data = call_gemini_fallback(doc_key, crop_path, raw_ocr_blocks, rows)
            if gemini_data:
                extracted_data = gemini_data

        final_doc_results = {}
        for _, template_id, row_num in rows:
            votes = extracted_data.get(str(row_num), {}).get("numeric", "0")
            cleaned_vote = clean_digit(votes)
            results_map[template_id] = cleaned_vote
            final_doc_results[template_id] = cleaned_vote

        checkpoint_log[doc_key] = {
            "used_gemini": used_gemini,
            "final_results": final_doc_results
        }
        with open(CONFIG["json_log_path"], "w", encoding="utf-8") as f:
            json.dump(checkpoint_log, f, ensure_ascii=False, indent=4)

        for vr in val_rows:
            vr["Gemini Triggered"] = used_gemini
            vr["Final Output Vote"] = final_doc_results.get(list(final_doc_results.keys())[int(vr["Row"])-1], "0") if int(vr["Row"]) <= len(final_doc_results) else "0"
            global_val_list.append(vr)

        pd.DataFrame(global_val_list).to_csv(CONFIG["validation_csv"], index=False, encoding='utf-8-sig')

        total_rows_processed += len(rows)
        if total_rows_processed - last_notified_rows >= 50:
            print(f"\n📊 --- Progress: ดำเนินการเสร็จสิ้นแล้วทั้งหมด {total_rows_processed} แถว ---")
            last_notified_rows = total_rows_processed

        # ล้าง GPU VRAM หลังจากจบแต่ละภาพ ป้องกัน OOM (Out of Memory)
        torch.cuda.empty_cache()

    try:
        df_template = pd.read_csv(CONFIG["csv_path"], encoding='utf-8-sig')
        df_template['votes'] = df_template['id'].map(results_map).fillna("0")
        df_template[['id', 'votes']].to_csv(CONFIG["output_csv"], index=False)
    except pd.errors.EmptyDataError:
        print("❌ Error: ไฟล์ CSV template ว่างเปล่า")

    shutil.make_archive('/content/cropped_images', 'zip', CONFIG["crop_dir"])
    print("\n🎉 DONE. Checkpoint, JSON, Validation Table, and Cropped Images are saved.")

if __name__ == "__main__":
    df_tmp = pd.read_csv(CONFIG["csv_path"], encoding='utf-8-sig')
    doc_groups = {}
    for idx, row in df_tmp.iterrows():
        p = parse_id(row['id'])
        dk = p.get('doc_key')
        if dk:
            if dk not in doc_groups: doc_groups[dk] = []
            doc_groups[dk].append((idx, row['id'], p['row']))

    image_map = {}
    for dk in doc_groups:
        files_found = []
        for f in os.listdir(CONFIG["img_dir"]):
            f_dk, f_page = get_doc_key_and_page(f)
            if f_dk == dk: files_found.append(os.path.join(CONFIG["img_dir"], f))
        image_map[dk] = sorted(files_found, key=lambda x: get_doc_key_and_page(os.path.basename(x))[1])

    process_pipeline(doc_groups, image_map)

    for f in [CONFIG["output_csv"], CONFIG["validation_csv"], CONFIG["json_log_path"], '/content/cropped_images.zip']:
        if os.path.exists(f): files.download(f)

"""# 2nd Data pipeline
- ตรวจสอบข้อมูลจาก main pipeline
- เช็คแถวที่เป็น 0 เรียก Gemini
- เช็ค Constituency (แบบแบ่งเขต) ถ้าคะแนนไม่เรียงจากมากไปน้อยเรียก Gemini
"""

import os
import json
import pandas as pd
from PIL import Image
from google import genai
from google.colab import userdata

# ==========================================
# 1. CONFIGURATION FOR SECOND PIPELINE
# ==========================================
print("🚀 เริ่มต้น Second Pipeline: Data Validation & Auto-Correction...")

drive_save_path = '/content/drive/MyDrive/OCR_Checkpoint'
JSON_PATH = f"{drive_save_path}/outputOCR.json"
CSV_TEMPLATE_PATH = "/content/submission_template_v4.csv"
REVISED_CSV_PATH = f"{drive_save_path}/Revised_submission.csv"
CROP_DIR = "/content/cropped_images"

# Load Gemini API
API_KEY = userdata.get("GEMINI_API_KEY")
client = genai.Client(api_key=API_KEY)

# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================
def parse_id(id_str):
    parts = id_str.split('_')
    if parts[0] == "constituency":
        return {"type": "constituency", "province": parts[1], "constituency": parts[2], "row": parts[3], "doc_key": f"constituency_{parts[1]}_{parts[2]}"}
    elif parts[0] == "party" and parts[1] == "list":
        return {"type": "party_list", "province": parts[2], "constituency": parts[3], "row": parts[4], "doc_key": f"party_list_{parts[2]}_{parts[3]}"}
    return {}

def call_gemini_revision(doc_key, crop_img_path, expected_rows, issue_msg):
    print(f"   🤖 Gemini Revision: {doc_key} (สาเหตุ: {issue_msg})")

    prompt = f"""
    คุณคือผู้ตรวจสอบความถูกต้องของข้อมูล (Data Auditor) สำหรับใบนับคะแนนเลือกตั้ง
    ระบบตรวจพบปัญหาในเอกสารชุดนี้: {issue_msg}

    หน้าที่ของคุณคือ:
    1. อ่านคะแนนจากรูปภาพใหม่อีกครั้งอย่างละเอียด (คาดหวังข้อมูลทั้งหมด {len(expected_rows)} แถว: แถวที่ {", ".join([str(r) for r in expected_rows])})
    2. แปลงตัวเลขให้เป็นฮินดูอารบิก
    3. หากแถวไหนมองไม่เห็นจริงๆ ให้ใส่ "0" แต่ต้องพยายามอ่านให้ครบก่อน
    4. ส่งกลับผลลัพธ์เป็น JSON format เท่านั้น ตัวอย่างเช่น:
    {{"data": {{"1": {{"numeric": "100"}}, "2": {{"numeric": "50"}}, ... }}}}
    """

    if not os.path.exists(crop_img_path):
        print(f"   ❌ ไม่พบรูปภาพที่ใช้ตรวจสอบ: {crop_img_path}")
        return {}

    img_content = Image.open(crop_img_path)

    try:
        # 🎯 ลองเรียกใช้ Gemini 3 flash ก่อนเสมอ
        resp = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=[prompt, img_content],
            config={"temperature": 0.0, "response_mime_type": "application/json"}
        )
        text_resp = resp.text.replace("```json", "").replace("```", "").strip()
        return json.loads(text_resp).get("data", {})

    except Exception as e:
        print(f"   ⚠️ Gemini 3 flash Error: {e}")
        print("   🔄 Switching to Gemini 2.5 flash for revision...")
        try:
            # 🎯 สลับมาใช้ Gemini 2.5 flash เมื่อ Flash เกิด Error
            resp_pro = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=[prompt, img_content],
                config={"temperature": 0.0, "response_mime_type": "application/json"}
            )
            text_resp_pro = resp_pro.text.replace("```json", "").replace("```", "").strip()
            return json.loads(text_resp_pro).get("data", {})

        except Exception as e_pro:
            print(f"   ❌ Gemini 2.5 flash also Failed: {e_pro}")
            return {}

# ==========================================
# 3. EXECUTE VALIDATION & REVISION
# ==========================================
if not os.path.exists(JSON_PATH):
    print("❌ ไม่พบไฟล์ outputOCR.json กรุณารัน Main Pipeline ให้เสร็จก่อน")
else:
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        ocr_data = json.load(f)

    revision_count = 0

    for doc_key, doc_info in ocr_data.items():
        final_results = doc_info.get("final_results", {})
        if not final_results:
            continue

        # เตรียมข้อมูลของแต่ละเอกสาร
        doc_type = parse_id(list(final_results.keys())[0]).get("type")

        # จัดเรียงข้อมูลตามแถว (Row)
        rows_data = []
        for t_id, vote_str in final_results.items():
            parsed = parse_id(t_id)
            try:
                row_idx = int(parsed['row'])
                vote_int = int(vote_str) if vote_str.isdigit() else 0
                rows_data.append({'row': row_idx, 'template_id': t_id, 'vote': vote_int})
            except Exception:
                continue

        rows_data.sort(key=lambda x: x['row'])
        expected_rows = [r['row'] for r in rows_data]
        votes_sequence = [r['vote'] for r in rows_data]

        # 🎯 เงื่อนไขที่ 1: มีค่าแถวไหนเป็น 0 หรือไม่?
        has_zero = any(v == 0 for v in votes_sequence)

        # 🎯 เงื่อนไขที่ 2: ถ้าเป็น Constituency ค่าต้องเรียงจากมากไปน้อย
        is_constituency_unsorted = False
        if doc_type == "constituency":
            sorted_descending = sorted(votes_sequence, reverse=True)
            if votes_sequence != sorted_descending:
                is_constituency_unsorted = True

        trigger_revision = False
        issue_msg = ""

        if has_zero:
            trigger_revision = True
            issue_msg = "พบแถวที่มีคะแนนเป็น 0"
        elif is_constituency_unsorted:
            trigger_revision = True
            issue_msg = "เอกสาร Constituency คะแนนไม่ได้เรียงลำดับจากมากไปน้อย"

        # 🎯 ถ้าติดเงื่อนไข ส่งให้ Gemini จัดการใหม่
        if trigger_revision:
            crop_img_path = os.path.join(CROP_DIR, f"crop_{doc_key}.png")
            gemini_revised_data = call_gemini_revision(doc_key, crop_img_path, expected_rows, issue_msg)

            if gemini_revised_data:
                revision_count += 1
                # อัปเดตข้อมูลกลับเข้า Dictionary
                for r_data in rows_data:
                    row_str = str(r_data['row'])
                    if row_str in gemini_revised_data:
                        new_vote = str(gemini_revised_data[row_str].get("numeric", "0"))

                        # ลบตัวอักขระที่ปนมากับตัวเลข
                        new_vote = re.sub(r'\D', '', new_vote)
                        if not new_vote: new_vote = "0"

                        # อัปเดตค่าใหม่
                        ocr_data[doc_key]["final_results"][r_data['template_id']] = new_vote

    # ==========================================
    # 4. SAVE UPDATED JSON & EXPORT REVISED CSV
    # ==========================================
    if revision_count > 0:
        print(f"\n💾 กำลังบันทึกข้อมูลหลังการซ่อมแซม... (อัปเดตไป {revision_count} เอกสาร)")

        # 1. เขียนทับ outputOCR.json เดิม
        with open(JSON_PATH, "w", encoding="utf-8") as f:
            json.dump(ocr_data, f, ensure_ascii=False, indent=4)

        # 2. เตรียมสร้าง Revised_submission.csv
        global_results_map = {}
        for doc_key, doc_info in ocr_data.items():
            for t_id, vote in doc_info.get("final_results", {}).items():
                global_results_map[t_id] = vote

        try:
            df_template = pd.read_csv(CSV_TEMPLATE_PATH, encoding='utf-8-sig')
            df_template['votes'] = df_template['id'].map(global_results_map).fillna("0")
            df_template[['id', 'votes']].to_csv(REVISED_CSV_PATH, index=False)
            print(f"🎉 เสร็จสิ้น! สร้างไฟล์ {REVISED_CSV_PATH} สำเร็จแล้ว")
        except pd.errors.EmptyDataError:
            print("❌ Error: ไฟล์ CSV template ว่างเปล่า")
    else:
        print("\n✅ ข้อมูลทุกเอกสารสมบูรณ์อยู่แล้ว ไม่พบจุดผิดปกติที่ต้องรันแก้ไขใหม่")

